### ISSUE TITLE
Java language support table/matrix

### ISSUE THREAD

**Issue by samuelgrigolato** [mauricioaniche/ck#13]
I was not able to find a Java version support table for your library, does it exist somewhere? If not, maybe it would be nice to have such information in your `README.md`.

**Comment by mauricioaniche** [comment]
This is indeed not clear in the README.

I had to re-visit the source code. It uses the JLS8 and JavaCore 1.8 as configurations for the JDT. See
https://github.com/mauricioaniche/ck/blob/master/src/main/java/com/github/mauricioaniche/ck/CK.java#L68 and L74.

A good PR would be to update this! 
- Change Maven POM to download the most recent version of JDT
- Change these two lines to the most recent version
- Make sure tests are green!

Are you up for it?
