### ISSUE TITLE
Method identifiers have commas, throwing off CSV parser

### ISSUE THREAD

**Issue by ayaankazerouni** [mauricioaniche/ck#17]
I've been playing with this a little bit this week. In the `method.csv` that is output, the method identifiers look something like this:

`getValue/3[int[],int[],String]`, which I guess maps to `name/#params[param1,param2,param3]`. This is good because, along with the `class` attribute, this gives you a unique identifier for the method.

However, the commas inside the square brackets are likely to throw off CSV parsers. Specifically, it looks to pandas like there are more values than fields in the line with the "extra" commas. I have confirmed that neither pandas nor R are able to read the file.

This can be dealt with with some file processing, but I think it would be better to output an "analysis-ready" file. Would you be open to a PR that changes those commas to some other character, say semi-colons?

**Comment by mauricioaniche** [comment]
Thanks for finding this bug! I always plug this CK tool with other Java tools, so that at the end, I produce my own CSV; maybe that's why I never faced this problem!

If you want to use an external library to generate a (always valid) CSV, I'm fine with one more dependency.
