### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by eriicf** [mauricioaniche/ck#19]
When try to use standalone version with command:
```
java -jar ck-x.x.x-SNAPSHOT-jar-with-dependencies.jar <project dir>
```
The program returns the following message:
```
log4j:WARN No appenders could be found for logger (com.github.mauricioaniche.ck.CK).
log4j:WARN Please initialize the log4j system properly.
```

**Comment by mauricioaniche** [comment]
Hmm, the jar I generated might not contain the log4j config file. 

My suggestion is for you to just add one manually and point it in the classpath.
