### ISSUE TITLE
Counting default fields

### ISSUE THREAD

**Issue by brunomateus** [mauricioaniche/ck#24]
Investigating the output of one experiment I found one weird behavior.
A class that has 36 fields, but with 0 public, private, protected and default fields.
I debugged and I found that all the fields were default, but the condition isDefault failed for all of them. 

I'm not an expert in JDT, so I don't know how to fix. I also added a new test case to ensure that the number of fields is equal to the sum of private, public, protected and default fields.

[File analyzed](https://raw.githubusercontent.com/TwidereProject/Twidere-Android/d819fa9bd1f2d0137e83ae0804928b62cba3ea40/twidere/src/main/java/org/mariotaku/microblog/library/twitter/model/TwitterStreamObject.java)

Output: 
* 36 fields
  * 0 public
  * 0 private
  * 0 default
  * 0 protected

**Comment by mauricioaniche** [comment]
Hi, @brunomateus, this was indeed a bug!

I just fixed it. Please, use the version that is in the master of this repo. I should release it to Maven soon.

**Comment by mauricioaniche** [comment]
ck-0.3.2 released

**Comment by brunomateus** [comment]
Thank you. I'll check it out.
