### ISSUE TITLE
Incorrect CBO for Generic Classes

### ISSUE THREAD

**Issue by aaghamohammadi** [mauricioaniche/ck#43]
Suppose we have a generic class ```Box```. The ```CBO``` returns 2 for the following class:
```java
public class Coupling6 {
    private Box<Integer> integerBox = new Box<Integer>();
}
```
However, I think it should return one.

**Comment by mauricioaniche** [comment]
CK indeed returns 1 here. See the test I just created for this: https://github.com/mauricioaniche/ck/commit/358b521283ba1a0424b196a323779ee34ef83969

If that makes sense to you, I'll close the issue.

**Comment by aaghamohammadi** [comment]
This is interesting! When you only create ```Coupling6```, the returned value is 2. However, when you create ```Coupling6``` plus ```Box``` the returned value is 1.

**Comment by mauricioaniche** [comment]
Yeah, that's what happens when you are creating 'fake' examples. If there are things that can't really be resolved, I try to approximate.

There was a bug in inexistent generic classes. Hopefully, I just fixed it: https://github.com/mauricioaniche/ck/commit/a69e34f84308043b2040fd7a59f400565683fe88

**Comment by mauricioaniche** [comment]
Wrote more tests, it seems to work, @aaghamohammadi 

https://github.com/mauricioaniche/ck/commit/2b63d1b6250fa04ca8ee1f8e8e5b576b7a704400

**Comment by aaghamohammadi** [comment]
This is strange. Really strange!

Consider the following code:
```java
public class Coupling61 {
	private Box2<Integer> integerBox = new Box2<Integer>();
}

public class Coupling62 {
	private Box2<A> integerBox = new Box2<A>();
}

public class Coupling63 {
	private Box<A> integerBox = new Box<A>();
} 
```
CBO is correct (1,2 ,2).

However, for the following code:
```java
public class Coupling61 {
	private Box<Integer> integerBox = new Box<Integer>();
}

public class Coupling62 {
	private Box2<Integer> integerBox = new Box2<Integer>();
}

public class Coupling63 {
	private Box<A> integerBox = new Box<A>();
}
```
CBO is incorrect (expected:1,1,2 --- output:1,1,1) .

**Comment by mauricioaniche** [comment]
Your `Coupling63` example is the same in both snippets. I tried one more combination there, and it works. 

Can you write a failing test?

**Comment by aaghamohammadi** [comment]
Yes. I have written a test that fails. I sent a pull request which includes that test.
