### ISSUE TITLE
Conflict between the implementation of RFC and the Original Paper

### ISSUE THREAD

**Issue by aaghamohammadi** [mauricioaniche/ck#51]
Hello,

I think there is a difference between your implementation of RFC and the original paper. In the paper, authors count the number of unique invocations plus **the set of all methods in the class** .

**Comment by mauricioaniche** [comment]
Yes, same here, I don't get why you would sum the methods in the class.

But that's easy to get if you really want the original RFC definition, as you can sum up RFC + total methods.

(I should make it explicit in the README that my goal was not to implement metrics as they were defined in the very old original paper, but more like a revised and pragmatic implementation of it)
