### ISSUE TITLE
New version(0.5.0) not working with maven plugin (delete pitest-maven as dependency )

### ISSUE THREAD

**Issue by magori** [mauricioaniche/ck#73]
The pitest-maven dependency has been added in version 0.5.0 (line 107 in the pom), it's a plugin and not a library.

	<dependency>
          <groupId>org.pitest</groupId>
          <artifactId>pitest-maven</artifactId>
          <version>1.4.11</version>
	</dependency>

I tryed to use the new version 0.6.2 with my maven plugin for CK, but it's not possible to compile anymore, because pitest-maven uses old maven libraries. ERROR : _The API of the mojo scanner is not compatible with this plugin version_.

I think it's very important to remove this dependency(too many sub-dependencies), but not the plugin, pitest is very cool to validate the tests.

**Comment by mauricioaniche** [comment]
That's indeed a problem!

I hope PR #75 will fix it!

**Comment by magori** [comment]
Yes this PR will fix it, Thank you
