### ISSUE TITLE
JGit dependency

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/ck#86]
Do we really need it?

**Comment by jeandersonbc** [comment]
Feels like *no* to me. Should we review the project dependencies for a cleanup?

**Comment by mauricioaniche** [comment]
Yes!

I am trying hard to remember why there's JGit here, but I can't find a good answer. Definitely a copy and paste mistake that's costing people some extra jars.

**Comment by mauricioaniche** [comment]
JGit is used by an integration test that actually clones an entire repository and runs CK there. The dependency is marked as test, so jars don't go to the final package! I just bumped all the versions of the dependencies; can't see any that's not used now.
