### ISSUE TITLE
how to cite this project if I am using it in my research?

### ISSUE THREAD

**Issue by lifeiliu** [mauricioaniche/ck#9]

**Comment by mauricioaniche** [comment]
Oh, I only saw it now. I have no paper about it, so cite my GitHub link ;)

**Comment by mauricioaniche** [comment]
Oh, I only saw it now. I have no paper about it, so cite my GitHub link ;)

**Comment by lifeiliu** [comment]
Thank you!

**Comment by evertonrenne** [comment]
> Thank you!

lifeiliu, did you publish a paper with ck tool?
