### ISSUE TITLE
How to get methods of inner classes in a class

### ISSUE THREAD

**Issue by EhsanMashhadi** [mauricioaniche/ck#98]
Hi,

I am using this library for research and I need to find the method-level metrics, so I am traversing the `CKClassResult` by using `getMethods` function to find the metric values of desired methods, but I have found that this method does not return methods that are inside of an inner class. Is there any way to get those methods?

Thanks

**Comment by mauricioaniche** [comment]
The tool supports inner classes. See this test: https://github.com/mauricioaniche/ck/blob/master/src/test/java/com/github/mauricioaniche/ck/MetricsPerClassesAndInnerClassesTest.java

Let me know if it worked for you.

**Comment by EhsanMashhadi** [comment]
Thanks for the answer. I tried to get the methods of the inner class by filtering the file name instead of the class name and it works.
